UPDATE BikeRacks_original
SET LATITUDE = ROUND(LATITUDE, 4),
    LONGITUDE = ROUND(LONGITUDE, 4)
    WHERE RACK_ID IS NOT NULL;
    
UPDATE DivvyStations_original
SET LATITUDE = ROUND(LATITUDE, 4),
    LONGITUDE = ROUND(LONGITUDE, 4)
    WHERE STATION_ID IS NOT NULL;
    
UPDATE CrashData_original
SET LATITUDE = ROUND(LATITUDE, 4),
    LONGITUDE = ROUND(LONGITUDE, 4)
    WHERE CRASH_RECORD_ID IS NOT NULL;
    
