USE bikes;
# File paths removed

# Bike Racks
LOAD DATA LOCAL INFILE "C:/Users/..."
INTO TABLE BikeRacks_original
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY "\n"
IGNORE 1 ROWS;

# Crash Data
LOAD DATA LOCAL INFILE "C:/Users/..."
INTO TABLE CrashData_original
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY "\n"
IGNORE 1 ROWS;

# Divvy Racks
LOAD DATA LOCAL INFILE "C:/Users/..."
INTO TABLE DivvyRacks_original
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY "\n"
IGNORE 1 ROWS;

# Divvy Trips
LOAD DATA LOCAL INFILE "C:/Users/..."
INTO TABLE DivvyTrips_original
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY "\n"
IGNORE 1 ROWS;

# Smart Location Data
LOAD DATA LOCAL INFILE "C:/Users/..."
INTO TABLE SmartLocation_original
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY "\n"
IGNORE 1 ROWS;

SHOW TABLES;
